{"uuid": "dd24bc19-d493-4bac-9b20-0e5d2845d120", "children": ["d9cde5ab-a75e-450e-9499-ec192ce2a08f"], "befores": [{"name": "open_web", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: failed to change window state to 'normal', current state is 'maximized'\n  (Session info: chrome=95.0.4638.54)\n\n", "trace": "  File \"D:\\python36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\TestTools\\python_project\\real_world_web_test\\test_case\\test_login.py\", line 23, in open_web\n    lp.get_url()\n  File \"D:\\TestTools\\python_project\\real_world_web_test\\base\\base_object.py\", line 19, in get_url\n    self.driver.maximize_window()\n  File \"D:\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 737, in maximize_window\n    self.execute(command, params)\n  File \"D:\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1635212010188, "stop": 1635212010317}], "start": 1635212010188, "stop": 1635212010554}