{"uuid": "c15ae57d-cab3-47fe-b670-c6518f309fa2", "children": ["df1e77d0-be9e-4201-9f9f-6e5a86b80360"], "befores": [{"name": "drivers", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'driver' referenced before assignment\n", "trace": "  File \"D:\\python36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\TestTools\\python_project\\real_world_web_test\\conftest.py\", line 18, in drivers\n    if driver is None:\n"}, "start": 1635211728572, "stop": 1635211728572}], "start": 1635211728572, "stop": 1635211728622}